### ISSUE TITLE
float formatting in data.csv

### ISSUE THREAD

**Issue by vergauwenthomas** [bmesuere/vlinder#610]
@bmesuere : updating the locations (and landcover) in the api/data.csv for a small sample of stations results in differences for other stations due to lack of float format. It might be more clear if we apply a float format, so differences in pull request are more representative. 

If you agree i suggest float format `'%.f6'`.
You can assign me to this if you would like.

**Comment by bmesuere** [comment]
Sure, this is a good suggestion.
