### ISSUE TITLE
Landcover and maps-creation

### ISSUE THREAD

**Issue by vergauwenthomas** [bmesuere/vlinder#916]
Maybe it is best to add the scripts for the creation of the maps and the landcover calculation to the repo? 

If you approve, then let me know where you want the script.

(*Ideally these scripts are runner in github workflow, but they use a large dataset (for landcover) that cannot be added to the repo. So it must be run locally.*)

**Comment by bmesuere** [comment]
Great idea! You can make a `scripts` directory in the root for this.

How large is the landcover dataset?

**Comment by vergauwenthomas** [comment]
> How large is the landcover dataset?

2,5GB
